source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'AlamoFire'

target 'Molib_Example', :exclusive => true do
  pod "Molib", :path => "../"
end

target 'Molib_Tests', :exclusive => true do
  pod "Molib", :path => "../"

  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', '2.0.0-rc.3'
  pod 'FBSnapshotTestCase'
end
